# Barebones template to ensure pipeline is triggered.

build:
  stage: build
  script:
    - echo "Nothing to build."

test:
  stage: test
  script:
    - pip install six==1.13.0
    - pip install -e .
    - pip install 'git+https://github.com/alexlatchford/pipelines@alexla/AIP-1676#egg=kfp&subdirectory=sdk/python'
    - pip install awscli click requests boto3 pytest
    - echo "Currently in the test stage."