# Barebones template to ensure pipeline is triggered
include:
  - project: 'analytics/artificial-intelligence/ai-platform/aip-infrastructure/ci-templates/ci-cd-template'
    ref: '837cf35e33594b94e84b732ccad15df16dfa9826'  # Pin to a commit/branch to prevent unwanted changes occurring.
    file: 'environments/devex.yml'
  - project: 'analytics/artificial-intelligence/ai-platform/aip-infrastructure/ci-templates/ci-cd-template'
    ref: '837cf35e33594b94e84b732ccad15df16dfa9826'  # Pin to a commit/branch to prevent unwanted changes occurring.
    file: 'blocks/aws.yml'


build:
  extends: 
    - .devex_internal_eks
    - .generate_kubeconfig
  variables:
    PIPELINE_VERSION: "1.0"
  stage: build

test:
  stage: test
  script:
    - ls
    - docker build .
