# Barebones template to ensure pipeline is triggered.

build:
  stage: build
  script:
    - echo "Nothing to build."

test:
  stage: test
  script:
    - pip install six==1.13.0
    - pip install -e .
    - pip install 'git+https://github.com/alexlatchford/pipelines@alexla/AIP-1676#egg=kfp&subdirectory=sdk/python'
    - pip install awscli click requests boto3 pytest pytest-xdist
    - export KFP_RUN_URL_PREFIX=https://kubeflow.corp.dev.zg-aip.net/
    - export KFP_SDK_NAMESPACE=aip-example
    - export METAFLOW_DATASTORE_SYSROOT_S3=s3://aip-example-dev/metaflow
    - export METAFLOW_DEFAULT_DATASTORE=local
    - export METAFLOW_USER=hariharans@zillowgroup.com
    - cd metaflow/plugins/kfp/tests
    - python --version
    - python3 --version
    - apt update
    - apt install python3.6
    - python3.6 -m pytest -s -n 2 run_integration_tests.py