# Barebones template to ensure pipeline is triggered
include:
  - local: '/environments/devex.yml'
  - local: '/blocks/aws.yaml'

build:
  extends: 
    - .devex_internal_eks
    - .generate_kubeconfig
  stage: build
  script:
    - docker build .
