# Barebones template to ensure pipeline is triggered
include:
  - project: 'analytics/artificial-intelligence/ai-platform/aip-infrastructure/ci-templates/ci-cd-template'
    ref: '024dcb2d169eeea2b3149f8bdeb3cf58f61e7ade'  # Pin to a commit/branch to prevent unwanted changes occurring.
    file: 'environments/devex.yml'
  - project: 'analytics/artificial-intelligence/ai-platform/aip-infrastructure/ci-templates/ci-cd-template'
    ref: '024dcb2d169eeea2b3149f8bdeb3cf58f61e7ade'  # Pin to a commit/branch to prevent unwanted changes occurring.
    file: 'blocks/aws.yml'
  - project: 'analytics/artificial-intelligence/ai-platform/aip-infrastructure/ci-templates/ci-cd-template'
    ref: '024dcb2d169eeea2b3149f8bdeb3cf58f61e7ade'  # Pin to a commit/branch to prevent unwanted changes occurring.
    file: 'blocks/docker.yml'

build:
  extends: 
    - .devex_internal_eks
    - .generate_kubeconfig
  variables:
    PIPELINE_VERSION: "1.0"
  stage: build
  script:
    - cp /root/.kube .
    - docker build -f metaflow/plugins/kfp/tests/Dockerfile -t metaflow-integration-testing:1.0 .
    - docker run 
        --rm 
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID 
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY 
        -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN 
        -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION 
        -e metaflow-integration-testing:1.0 
        bash -c "
          export KFP_RUN_URL_PREFIX=https://kubeflow.corp.dev-k8s.zg-aip.net/ && 
          export KFP_SDK_NAMESPACE=aip-example && 
          export METAFLOW_DATASTORE_SYSROOT_S3=s3://aip-example-dev/metaflow/ && 
          export METAFLOW_DEFAULT_DATASTORE=local && 
          export METAFLOW_USER=talebz@zillowgroup.com && 
          cd /metaflow/metaflow/plugins/kfp/tests && 
          python -m pytest -s -n 2 run_integration_tests.py
        "
